{% set name = "libzip" %}
{% set version = "1.10.0" %}
{% set sha256 = "52a60b46182587e083b71e2b82fcaaba64dd5eb01c5b1f1bc71069a3858e40fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://libzip.org/download/libzip-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-bz2-pkgconfig-win.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - cmake
    - make                               # [not win]
    - perl 5.32.*  # avoid making a matrix of perl builds
    - {{ compiler('c') }}
  host:
    - zlib
    - bzip2
    - openssl
    # perl is needed to run the package tests

test:
  commands:
    - test -f ${PREFIX}/bin/ziptool  # [linux or osx]
    - test -f ${PREFIX}/lib/libzip.so  # [linux]
    - test -f ${PREFIX}/lib/libzip.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\\ziptool.exe exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\zip.lib exit 1  # [win]

about:
  home: https://libzip.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A C library for reading, creating, and modifying zip archives.
  description: |
    libzip is a C library for reading, creating, and modifying zip archives.
    Files can be added from data buffers, files, or compressed data copied
    directly from other zip archives. Changes made without closing the
    archive can be reverted. The API is documented by man pages.
  doc_url: https://libzip.org/documentation/
  dev_url: https://github.com/nih-at/libzip

extra:
  recipe-maintainers:
    - ceholden
    - traversaro
