# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tGIAy0ECifJOHMKMl+gz3NTBL1EcuVBzOnHburHtmSwk9EBrgbAKAkgjPAw93jXXd32eklNUK9lKtnZtt05Hb9t38ZwK3XtrtpXKTj0pii1JH7lr3XBVK4pdcbo3GJJ8bG4QnWEOmh2djtlzmlbdsSPC3nzWRDpDnmxPIux4h41oYc3G6tDEzJ+vY+SG9NmhWBbCiyrGxar4BBTsY34oewIaiQg0fYgR0mMNLtLPgKhwUG6UyhnkX3eCBIO4RXnyI6i9SqWe2JOAE2VwX3Mt/RhzkdyGbY4R1VCv3yjVuuSL9jmbnP15YY7zikOmtDZvXBt9KWCMVhCaWS9oVRBbhWF9VkunHZZNrY5Lq/3IfV4IHiUAAT2JU37x27c4J+P9Dh/rOAB6Zd9oQbcp8Sm/muDEns22wkE66kVWdXGPOoh/a9BWu/ODuM1vuW1Si32ktg60MZ93Xcc+N0B4Alvxc1Cfu3xf4YCmOgJz3DIkjiwPG8fEkYiG08u+sx2N1PkqQ5IMZgqleRcyWOTJ++AdPA491upxf7DFSGImDvTq8JYU93cbLoIy6+Xy3giVYjv5XRFcGyEi+zL3sPX4Z3hscXwYBwuWBNYTXnOw6+6Lscx+xTFXnPJKvnGhJc3wlZLRYAPDcWJ/HbDx6cBzeXldftk99CxeMnxIpS0I20c+fmU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
