appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tGIAy0ECifJOHMKMl+gz3NTBL1EcuVBzOnHburHtmSwk9EBrgbAKAkgjPAw93jXXd32eklNUK9lKtnZtt05Hb9t38ZwK3XtrtpXKTj0pii1JH7lr3XBVK4pdcbo3GJJ8bG4QnWEOmh2djtlzmlbdsSPC3nzWRDpDnmxPIux4h41oYc3G6tDEzJ+vY+SG9NmhWBbCiyrGxar4BBTsY34oewIaiQg0fYgR0mMNLtLPgKhwUG6UyhnkX3eCBIO4RXnyI6i9SqWe2JOAE2VwX3Mt/RhzkdyGbY4R1VCv3yjVuuSL9jmbnP15YY7zikOmtDZvXBt9KWCMVhCaWS9oVRBbhWF9VkunHZZNrY5Lq/3IfV4IHiUAAT2JU37x27c4J+P9Dh/rOAB6Zd9oQbcp8Sm/muDEns22wkE66kVWdXGPOoh/a9BWu/ODuM1vuW1Si32ktg60MZ93Xcc+N0B4Alvxc1Cfu3xf4YCmOgJz3DIkjiwPG8fEkYiG08u+sx2N1PkqQ5IMZgqleRcyWOTJ++AdPA491upxf7DFSGImDvTq8JYU93cbLoIy6+Xy3giVYjv5XRFcGyEi+zL3sPX4Z3hscXwYBwuWBNYTXnOw6+6Lscx+xTFXnPJKvnGhJc3wlZLRYAPDcWJ/HbDx6cBzeXldftk99CxeMnxIpS0I20c+fmU=}
